In [2]:
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [8]:
# input dataset
X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1] ])

# output dataset           
y = np.array([[0,1,0,1]]).T

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1

print "Original weights"
print syn0

for iter in xrange(10):
    # forward propagation
    l0 = X
    print "l0"
    print l0
    
    l1 = nonlin(np.dot(l0,syn0))
    print "l1"
    print l1
    
    # how much did we miss?
    l1_error = y - l1
    print "Missed by:"
    print l1_error
    
    # multiply how much we missed by the
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)
    print "l1 delta"
    print l1_delta
    
    # update weights
    syn0 += np.dot(l0.T,l1_delta)
    print "----------------------------------"

print "Output After Training:"
print l1

Original weights
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
l0
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
l1
[[ 0.2689864 ]
 [ 0.36375058]
 [ 0.23762817]
 [ 0.3262757 ]]
Missed by:
[[-0.2689864 ]
 [ 0.63624942]
 [-0.23762817]
 [ 0.6737243 ]]
l1 delta
[[-0.05289153]
 [ 0.14725108]
 [-0.04304896]
 [ 0.14809799]]
----------------------------------
l0
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
l1
[[ 0.30994795]
 [ 0.4839144 ]
 [ 0.29707415]
 [ 0.468723  ]]
Missed by:
[[-0.30994795]
 [ 0.5160856 ]
 [-0.29707415]
 [ 0.531277  ]]
l1 delta
[[-0.06629173]
 [ 0.12888786]
 [-0.06203535]
 [ 0.13229953]]
----------------------------------
l0
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
l1
[[ 0.33905633]
 [ 0.58168226]
 [ 0.3411564 ]
 [ 0.58395738]]
Missed by:
[[-0.33905633]
 [ 0.41831774]
 [-0.3411564 ]
 [ 0.41604262]]
l1 delta
[[-0.07598155]
 [ 0.10178842]
 [-0.07668128]
 [ 0.10107804]]
----------------------------------
l0
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
l1
[[ 0.35039606]
 [ 0.64170066]
 [ 0.35811735]
 [ 0.6